### ISSUE TITLE
Unsure bright sky tiles that fell through the cracks

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#100]
We somehow lost track of several bright tiles marked unsure.  Most of these are due to bright skies and large sky residuals, though a few other reasons are noted.  We need to mark these as bad and reprocess them.  Affected tiles:
- 20662, 20220915/142569
- 20698, 20221207/156880 (there's also a later exposure that is not problematic and should be kept)
- 23014, 20221008/146763 (very slow?)
- 23329, 20220914/142436
- 23954, 20221106/152201, 152202, 152203 (bad guiding + missing cryostats leads to 4 missing petals)
- 24883, 20220914/142438
- 26167, 20220914/142437
@marcelo-alvarez , @akremin , would either of you be able to rerun these?  Thanks!

**Comment by schlafly** [comment]
Can we try to clean these up?  Thanks!

**Comment by akremin** [comment]
I did the work for this last week, but NERSC has been completely unusable. It took 3+ hours to delete ~10 directories and submit ~40 jobs... something that should have taken a few minutes.

Needless to say many of the jobs timed out and I'd rather only do a cleanup sweep once since it requires some special care. I'm waiting for stability, which I had hoped would come after both computers were down for maintenance, but today doesn't appear to be any better.

**Comment by schlafly** [comment]
Ugh, I didn't realize NERSC had been so bad lately, thanks.

**Comment by akremin** [comment]
I was treating these as a subset of some other cleanup work. It turns out that none of the tiles here had other non-flagged exposures on the nights in question, so the cleanup is actually done (the failing jobs were for other tiles unrelated to this issue). 

I have flagged the above exposures as bad, removed the files from daily, rerun one set of tile redshifts from a later night for a flagged tile, and rerun the tsnr afterburner and nightqa for all the impacted nights.

Back to you @schlafly

**Comment by schlafly** [comment]
I've cleared QA on these; closing.
