### ISSUE TITLE
Two tiles from 20230409 with high SKY2CHIPDF marked unsure

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#108]
Some potential sky subtraction issues in the following tiles:
- MAIN DARK tile 10383, exp 175639: some bright blobs in b0 and b9 sframesky, resulting in SKYCHI2PDF of 2.49 and 3.05. Marked **unsure**.
- MAIN BRIGHT tile 24902, exp 175661: clouds produced elevated fluxes in sframesky (mostly r and z cameras), SKYCHI2PDF warnings for z3, z4, z6, r6. Chi-square values are 1.5 to 1.6. Marked **unsure**.

Note: MAIN BRIGHT tile 24897, exp 175660 also had some clouds visible in sframesky but no chi2 warnings, so marked as good.

Sky fiber fluxes copied below for exp 175639:
![Screen Shot 2023-04-10 at 3 01 19 PM](https://user-images.githubusercontent.com/7385438/230977007-cad2d833-72a5-4638-9684-db645547cfd7.png)

Sky fiber fluxes for exp 176661:
![Screen Shot 2023-04-10 at 3 10 05 PM](https://user-images.githubusercontent.com/7385438/230977354-4bd58cef-2f5d-414e-a2bc-448951aa2296.png)

**Comment by schlafly** [comment]
For these alerts we look more carefully at the redshift distributions and try to decide if they look compromised.  I don't see any issues on these tiles.  The dark tile 10383 is affected by the bright star in the middle of P0; since this is a "problem with the sky", we just mark these as good.  For 24902 it's just the sky being bright / being close to the moon / sky subtraction being problematic.  One can faintly detect a few more sources than usual being assigned redshifts at z ~ 1.8.  But we've been keeping tiles like this.

Let's mark both of these as good as part of tomorrow's QA and then close the ticket.  You can see these again by passing a --tileids argument to desi_tile_vi.  Thank you!

**Comment by sybenzvi** [comment]
Updated tiles 10383 and 24902 from unsure to good while waiting for nightqa to finish.
