### ISSUE TITLE
Tile 23530, exp 175900 lost amp r4b due to cosmics

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#110]
In exp 175900 on 20230411, amp r4b was masked out in online and offline preprocessing. The [Nightwatch log](https://nightwatch.desi.lbl.gov/20230411/00175900/qproc-r4-00175900-logfile.html) and CCD images suggest a subshower hit the chip:  
```
WARNING:preproc.py:1024:preproc: Camera r4 amp A, ignore overscan rows = [1942 1943 1944 1945 1946] because of large charge deposit = [ 1154.72580645 10724.17741935 30934.01612903 4397.29032258
```

The warnings weren't noted in the nightlog, but the affected fibers in r4 have bad QAFIBERSTATUS in offline processing so it's easy to see in tile QA. Marking the tile **unsure** in case reprocessing is needed.

![Screen Shot 2023-04-12 at 4 56 20 PM](https://user-images.githubusercontent.com/7385438/231584396-707be03d-94ff-4457-825e-b781bd17c27e.png)

**Comment by schlafly** [comment]
This looks like a case where we lose an amp due to a CR causing too much difficulty in the overscan region.  Julien went through a lot of iterations trying to handle that case, but it proved hard to do robustly.  We've just been accepting that occasionally we lose an amp.  I would mark this as good---the one amp with somewhat problematic data is masked.  We could do better but that's future development with a long lead time, and we certainly want to keep the exposure.

**Comment by sybenzvi** [comment]
OK, marking this as good and closing the issue.
