### ISSUE TITLE
Tile 7471 on 20230512 has a serie ~30 dubious redshifts

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#117]
tileid 7471 (expid=180299 on 20230512) has been marked as unsure, as it has a suspicious patch of approx. 30 spectra at z~0.065 at 3400<fiber<3500, with the redshift drifting with fiber.
there s a peak at ~5300A in the spectra, even in the stuck-sky ones, which is interpreted as oiii.
I attach one example; the ~30 spectra are available here: https://data.desi.lbl.gov/desi/users/raichoor/tmpdir/tmp-7471-thru20230512-dubious.pdf.
![tmp](https://github.com/desihub/desisurveyops/assets/61986357/1ed3c500-07a7-4161-84b9-77b740a23dfa)
<img width="1377" alt="Screenshot 2023-05-13 at 11 47 43 AM" src="https://github.com/desihub/desisurveyops/assets/61986357/3263a337-8c3c-45d5-897f-259099a66dfc">

**Comment by djschlegel** [comment]
This is due to a very strange CCD-level event on B6 originating at (x,y) ~ (4048,3067), then bleeding to the left.  It's not a sharp enough feature to be flagged as a CR.  Not sure I've seen anything like this before.

<img width="505" alt="Screenshot 2023-05-13 at 10 49 49 PM" src="https://github.com/desihub/desisurveyops/assets/7918018/c6ce3914-128b-44b4-b43c-59ac9ecec6db">

**Comment by sbailey** [comment]
While I'm normally hesitant to add special case handling of rare events, we could consider something like a desi_spectro_calib extramask.csv file that would define
```
NIGHT EXPID CAMERA XMIN XMAX YMIN YMAX COMMENT
```
The code could use that to add an extra per-exposure per-camera custom CCD mask, to use for cases like this to flag a small patch of the CCD instead of having to discard the entire amp.

**Comment by schlafly** [comment]
We discussed this in the DailyOps meeting today.  The outcome is that we wanted to leave this open for one week to see if handling along the lines Stephen suggests would be straightforward.  If so, reprocess with that feature.  If not, mark the amp as bad and reprocess.

**Comment by sbailey** [comment]
This tile 7471 has been reprocessed and tsnr/tiles-daily rerun for 20230512 using the fix from desihub/desispec#2048.  i.e. it is ready for QA again.  @schlafly or others, please close this ticket after the tile is accepted, or otherwise post any remaining problems found.

![image](https://github.com/desihub/desisurveyops/assets/218471/8b789293-1345-46c1-9fb7-f184fd3d57b1)

**Comment by schlafly** [comment]
Marked good, closing!
