### ISSUE TITLE
Bad exposure 202920

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#157]
Hi @akremin @abhi0395, can you mark exposure 202920 (tile 83423) from 20231031 as bad? (Guiding was lost during that exposure.)

**Comment by sbailey** [comment]
@rongpu I'm on daily dataops duty now, so I'll flag that as bad.  Thanks for catching that.

**Comment by sbailey** [comment]
I flagged night=20231031 expid=202920 tile=83423 as bad and purged it.  That tile was also observed on 20231101 expid=203052, so I also purged and reran that so that the cumulative redshifts won't have the bad 20231031 data.  I reran tsnr and nightqa for both nights.

@rongpu @schlafly heads up: this tile is still listed in tiles-specstatus as EFFTIME_SPEC=275.3, albeit with ZDONE=false QA=none, though now after purging it is listed in tiles-daily as EFFTIME_SPEC=241.2 .  I've lost track of what the procedure is here to get tiles-specstatus in sync with tiles-daily.  I can figure it out if you don't immediately know either.

```
tiles-specstatus:
TILEID EFFTIME_SPEC GOALTIME ZDONE  QA 
------ ------------ -------- ----- ----
 83423        275.3    300.0 false none

tiles-daily:
TILEID EFFTIME_SPEC
------ ------------
 83423        241.2

exposures-daily:
 NIGHT   EXPID  TILEID EXPTIME EFFTIME_SPEC
-------- ------ ------ ------- ------------
20231031 202920  83423   530.5          0.0
20231101 203052  83423  1077.2        241.2
```

**Comment by schlafly** [comment]
tiles-specstatus will get updated automatically the next time desi_update_tiles_specstatus is run as part of QA.  Don't worry about it.  Thank you!  241.2 is short of 0.85 * 300 = 255 so we should technically put this one back into the night plan for another 60 s.  @rongpu, would you mind doing that for tonight?  Ugh, I thought these were done.  Thanks!

**Comment by rongpu** [comment]
The remaining observation on tile 83423 was completed 20231103. @schlafly I think we can close this issue now.

**Comment by schlafly** [comment]
Thanks, closing!
