### ISSUE TITLE
P4 had 250 fibers out of action on 20231113, tileid 21279, 22848, 6530

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#161]
P4 had 250 fibers out of action on 20231113, 21279, 22848, 6530.  These were recovered later in the night.  We're concerned that some things look a little weird with the number of standard stars being large on these tiles, but I expect we'll accept them in the end.

**Comment by araichoor** [comment]
sorry I only see now this ticket.
I ve answered in slack (https://desisurvey.slack.com/archives/C01HNN87Y7J/p1699978991301089), but I re-post here for better book-keeping.

in short : these look good to me.

in details:
- I confirm the standard stars tile-qa diagnosis (for tileid=6530, we ve been lucky that only 2/10 std stars fall in the bad region!):
![tmp-6530-thru20231113](https://github.com/desihub/desisurveyops/assets/61986357/be8a148c-ab13-4edb-a185-8a2fd0758111)
![tmp-21279-thru20231113](https://github.com/desihub/desisurveyops/assets/61986357/9d86e9a4-bd6c-4463-a567-956fbde76e40)
![tmp-22848-thru20231113](https://github.com/desihub/desisurveyops/assets/61986357/befe2547-575a-4724-aad4-92ed6fc53dac)
- the `PETALQA` `EFFTIME_SPEC` value is the median of the 500 fibers: so it makes sense its either 0 (tileid=22848 and 6530) or a low value (62s for tileid=21279); as far as we know, that quantity is not used downstream;
- the `BADPETALPOS` flag is not turned on, because we request that 60% of the fibers to have positioning issue to turn it on (https://github.com/desihub/desispec/blob/aae1e5050ccef189bf529ff020a1b1ad4b725999/py/desispec/data/qa/qa-params.yaml#L11-L13);

**Comment by schlafly** [comment]
Okay, redoing QA here to mark these as good, closing!
