### ISSUE TITLE
Tile 8257 half amp marked bad due to spurious amp jump

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#164]
This isn't a new problem, similar to issue #14.

Tile 8257 exposure 208688 on 2023-12-08 triggers the "b6 amp D OSTEP=5.5 too large" error, rejecting the right half of the CCD in processing.  The underlying cause is a saturation event at (2539,3994) in the raw image that bleeds left into the overscan region.

I've marked this tile as "unsure" for now.

**Comment by djschlegel** [comment]
<img width="498" alt="Screenshot 2023-12-09 at 9 43 17 AM" src="https://github.com/desihub/desisurveyops/assets/7918018/8469628f-702c-4994-9d26-fc63bb4cd9d1">

**Comment by sbailey** [comment]
I think the fix is to identify the region to mask and add it to $DESI_SPECTRO_CALIB/ccd/ccd-region-mask.csv, then reprocess.  See desihub/desispec#2050 for context.  We might need to mask entire rows to avoid triggering the "b6 amp D OSTEP=5.5 too large" error. 

Assigning myself to followup on this after catching up on daily ops (and likely not until later in the collab mtg or the following week).

**Comment by schlafly** [comment]
@sbailey , pinging this ticket.

**Comment by schlafly** [comment]
Pinging this ticket...

**Comment by sbailey** [comment]
Brief update: this is more complicated than just masking pixels with $DESI_SPECTRO_CALIB/ccd/ccd-region-mask.csv, because that only masks in the active region but not the overscan region.

[`find_overscan_cosmic_trails`](https://github.com/desihub/desispec/blob/main/py/desispec/preproc.py#L639) was intended to find cases like this, but isn't getting triggered by this particular case.  I think the solution for this case will be to:
  * mask all columns for that amp for the impacted rows (there is also a negative shadow rightward of the bright streak leftward, so masking all of them is motivated since the shadow correction isn't working great for them anyway).
  * add additional preproc code to ignore overscan rows where all of the active region data for those rows are masked so that it won't trigger OSTEP for rows that are masked anyway.

**Comment by sbailey** [comment]
@schlafly tile 8257 is re-processed in daily, recovering b6 (though petal 1 was still marked as bad that night due to bad z1):
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/8257/20231208/tile-qa-8257-thru20231208.png

**Comment by schlafly** [comment]
This was closed and I lost track of it, but FWIW, I just marked this tile as good.
