### ISSUE TITLE
Tile 20684 from 20231228 has a gradient in EFFTIME, and a small bump around z~1.3

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#171]
![tile-qa-20684-thru20231228](https://github.com/desihub/desisurveyops/assets/1065981/b6980fc3-37ad-41eb-af35-06cd7d871eb2)

sframesky:

<img width="959" alt="1" src="https://github.com/desihub/desisurveyops/assets/1065981/ce3f7af2-435c-42ae-87d2-9cb2bd3facaf">

**Comment by schlafly** [comment]
The bump at z = 1.3 is on z3 and so doesn't really bother me, I think; it's the usual CTE effect.  The gradient in EFFTIME is worth diagnosing, though, so let's leave this unsure for now.

**Comment by djschlegel** [comment]
The sky was actually getting significantly brighter over the 20 min of the exposure.  In the attached ETC sky brightness plot, this is the exposure starting at 4:58 UT.  So the S/N gradient is likely due to a sky gradient.
<img width="584" alt="Screenshot 2024-01-08 at 2 59 58 PM" src="https://github.com/desihub/desisurveyops/assets/7918018/d34224ea-dc94-46e8-a05f-c266acdefe70">

**Comment by schlafly** [comment]
Thanks David.  I agree, given the large sky value and gradient, and remembering now that we do build the sky gradient into the EFFTIME, I'm happy to close this.  I'm marking good and closing.
