### ISSUE TITLE
0th mag star on tile 11594

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#179]
We observed dark tile 11594 on 2024-02-18 which contained alpha Boo, a 0th mag star.  This effects the sky subtraction and s/n on petal 1.  We should look more carefully at those redshifts.  Note the observing conditions were perfect (photometric, 0.9 arcsec seeing), so we're unlikely to re-observe in any better conditions.

![tile-qa-11594-thru20240218](https://github.com/desihub/desisurveyops/assets/7918018/f15b93b0-d872-435f-8494-2ad125f9354d)

**Comment by araichoor** [comment]
from the efftime plot, it looks like ~half of the petal 0 also is a bit affected, i.e. has lower snr.

**Comment by schlafly** [comment]
We usually just accept "the sky is wrong" petals for MTL purposes.  Yes, things will be worse here, but we don't know of a reprocessing that improves it?  That would be my inclination here as well.

I don't think there's a world where we improve handling of very bright stars to improve the processing here in the short term.  We could mark the whole petal as bad.  I imagine (but don't know!) that LSS already must be doing some serious masking around the very bright stars since they clearly do impact the spectra and imaging.  We can discuss on the call tomorrow but as a matter of policy I think we have been saying these are okay.

**Comment by schlafly** [comment]
I marked this as good in QA following the discussion on the call today.
