### ISSUE TITLE
All tiles observed on the night of 20240327 marked as unsure due to a problem with z7.

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#186]
After going back on sky on `20240327` we discovered a problem in z7, due to a known clock phase problem.

We therefore marked all tiles observed on `20240327` as bad in preparation for re-processing.

The issue is described in a thread [on Slack](https://desisurvey.slack.com/archives/C01HNN87Y7J/p1711672286707949).

**Comment by schlafly** [comment]
@akremin , @abhi0395 , we'll need to reprocess these after marking half of z7 as bad.  @julienguy , it's not clear to me right now what the right terminology is for the different amplifiers (this is in two amp mode), and which is the problematic one; most of what we see in QA is the discontinuity between the amps and less which one is wrong.

**Comment by sbailey** [comment]
The amp names are defined by which CCDSECx, BIASSECx header keywords exist.  In the case of z7 on 20240328 this is x=C and D amps.  i.e. we are in 2amp mode, reading out the charge through the two amps at the top that were named C and D in 4amp mode, and amps A and B at the bottom are not used.

In this particular case, although we are reading out only through amps C and D at the top of the CCD, there was a clocking problem on the bottom half of the CCD on both the left and the right, i.e. the regions that used to be read out through amps A and B, but the problem here is with the clocks, not with amps A and B per-se.  So we shouldn't flag amps A and B as bad because those don't exist as far as the headers are concerned.

**Comment by schlafly** [comment]
Do we have a mechanism to flag what used to be A&B as bad, or do we just throw out all of z7?

**Comment by akremin** [comment]
We can flag portions of the CCD on a per-exposure basis, but it's not a simple process and that method would not currently trigger a fiberstatus or zwarn flag. Discussing with Stephen we both agreed that is wasn't worth pursuing (for now at least).

@rongpu we will need to flag z7 as bad. Because all exposures are impacted, please mark all of petal 7 as bad ("a3"). In your comment string please specify that z7 is the actual problem, e.g. "z7 clock issue leads to a7 being bad". That way a human in the future will know what was actually bad.

After flagging, we'll need to purge the night and rerun.

**Comment by rongpu** [comment]
Reprocessing for 20240327 is complete with petal 7 flagged as bad for all tiles.

**Comment by schlafly** [comment]
@SGontcho , would you mind re-QAing this night?  Something like desi_tile_vi --night 20240327 --qastatus all should do it.

**Comment by schlafly** [comment]
I redid QA on this night, looks good, closing.
