### ISSUE TITLE
archive status of 22432 with missing petals for different reasons

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurveyops#194]
daily/tiles/cumulative/22432/20230507 -> ../../archive/22432/20230908 is missing petals 4 and 8.  Petal 4 exists in the data but is flagged as bad and thus not processed, while petal 8 was not in the ICS instance and thus no raw data exist.

At the archive level, we do have a zmtl-4-22432-thru20230507.fits flagging all targets as bad for the purposes of an MTL update.  However, we do *not* have an equivalent zmtl-8 file, which I suspect is an oversight.  I would have expected that we should have created an "everything is bad" zmtl file for petal 8 as well.

@geordie666 @schlafly can you check the status of this?  i.e. what happened to petal 8 targets in the MTL?

**Comment by schlafly** [comment]
@geordie666 will know better than I do.  But just reading what you've written, then petal wasn't in the instance and so we never had observations or data for those targets, and so we never updated the MTL with them, which is correct, since they were never observed?

**Comment by geordie666** [comment]
I agree with @schlafly: This is also my read on what should have happened. I'll check carefully, though.

**Comment by geordie666** [comment]
I've checked. Eddie is correct. There are no updates for Petal 8 in the re-archiving because a file for Petal 8 never existed in the first place in the archiving. 

The reason the file for Petal 4 exists is because we needed to _update_ Petal 4 to indicate that all of the observations were `BAD_SPECQA` as the targets on Petal 4 had already entered into the MTLs in this file:

```
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/archive/22432/20230616/zmtl-4-22432-thru20230507.fits
```

So, everything is working as expected here. We don't necessarily need a bad petal to exist when we _archive_ data. But we _do_ need a bad petal to be indicated when we _re-archive_ data if the petal was previously partially recorded as good.

Anyway, I think we can close this and move on. This is the expected behavior.

**Comment by sbailey** [comment]
Thanks.  Our jura checks were driving us towards inspecting cases that had zmtl but no redrock files, and I incorrectly came to the conclusion that we were always creating "everything is bad" zmtl files for existing-but-bad data.  Upon further investigation, we are only creating those files for the "existing and previously archived but retroactively determined to be bad" data.
