### ISSUE TITLE
Bright tiles 25915 and 21779 affected by CTE in r7

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#197]
As I mentioned on slack, the two tiles have spurious BGS redshifts in petal 7, presumably caused by residual CTE in r7.
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25915/20240607/tile-qa-25915-thru20240607.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21779/20240608/tile-qa-21779-thru20240608.png
They are currently marked as "unsure" in QA.

**Comment by schlafly** [comment]
We discussed this in the survey-ops meeting today.  The decision was to go ahead and count these as "good" and MTL them.  Yes, this is the CTE in r7 not being well treated by the "simple" CTE correction.  Applying the more advanced correction is somewhat more challenging than usual because this is a 2-amp mode device.  But I think we can change the calibration procedure to handle this case (e.g., by taking the 100 s flat, divided by 100, as the "truth" image for the CTE-affected image).  Since these bright tiles only get single observations of targets it isn't too bad to accept them but then mark them bad later in LSS if needed.

So let's mark these as good and proceed with an archiving & MTL update tomorrow.

@forero

**Comment by forero** [comment]
Marked as good.
