### ISSUE TITLE
Near moon observations

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#208]
We observed a few tiles closer to the moon than we normally do, following the engineering full moon observations at the end of August.  The following expid were observed closer than we normally are willing to go:

```
EXPID  TILEID  NIGHT   MOONSEP
int64  int64   int64   float64
------ ------ -------- -------
249647  27122 20240821   38.32
249648  27122 20240821   38.45
249649  27156 20240821   35.91
249650  27117 20240821   36.28
249651  27117 20240821   36.33
249657  27116 20240821   37.54
249661  20801 20240821    36.3
249819  25977 20240822   35.25
249820  25977 20240822   35.34
249823  24589 20240822    37.7
249824  24589 20240822   37.68
249825  27777 20240822   38.06
250082  11419 20240824   36.95
250083  11419 20240824    37.1
250085  20674 20240824   36.75
```

The bright observations on 20240821 look pretty nominal to me, though there are some RSKYTHRUFRAC warnings that may be related but don't seem to be affecting redshifts.  Likewise 20240822 looks pretty nominal to me.

On 20240824 we observed a dark tile, 11419.  QA looks fine but it reports a low n(z) / n(z)_ref.  My suspicion is that this is just typical for bright sky & good seeing conditions but I'm making that up.  We could throw it away just to not have any dark tiles too near the moon.  The final exposure 250085 has lots of skychi2pdf warnings and spurious redshifts and we should throw it away.

@ashleyjross , you were annoyed by other exposures on something like 20240824; can you say which ones?

**Comment by araichoor** [comment]
few additional infos about tileid=11419:

that tile actually got one extra exposure on 20240825 (probably because we ran ap with `--no-network`, so nts used `efftime_etc`, which underestimates `efftime_spec` when the moon is up), and got in the end `efftime_spec~1300s`.
with that extra-exposure, the coadds look nominal to me.

@ashleyjross and me exchanged various diagnoses in this thread: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1724704469175409.

for completeness:

here s the tile-qa for 20240824 (another diagnosis: only 93% of lrgs have deltachi2>25):
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/11419/20240824/tile-qa-11419-thru20240824.png
![tile-qa-11419-thru20240824](https://github.com/user-attachments/assets/912aa752-6aee-4351-8ed6-2dbeab77e4b8)

and here s the tile-qa for 20240824+25 (another diagnosis: 97% of lrgs have deltachi2>25, a nominal value):
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/11419/20240825/tile-qa-11419-thru20240825.png
![tile-qa-11419-thru20240825](https://github.com/user-attachments/assets/e1e36e03-48df-4e39-888f-c967e38bd543)

**Comment by schlafly** [comment]
Thanks Anand.  Note that the EFFTIME discrepancies don't seem so large, ~20%, so fairly typical for moon and not special about this tile.  So I would have said that 11419 is pretty nominal on the basis of the QA and we should keep it.  If I were better I would try to map out n(z) / n(z)_ref as a function of sky brightness and EFFTIME_SPEC to see how weird that n(z) / n(z)_ref looks in that context, but that sounds like a fair amount of work.  @ashleyjross , do you want to say if you want to keep this tile or not?  My default is to keep it as I can't see any issues with the data.

**Comment by ashleyjross** [comment]
The extra exposure on the 25th makes it more typical in terms of success and having gotten that exposure, it is probably fine. The evidence suggests to me that EFFTIME_ETC was actually more correct in terms of predicting the S/N for this tile than EFFTIME_SPEC. So, the ultimate EFFTIME_SPEC (or TSNR2) might be suspect for this tile. The other tile I flagged was 1135, which also got another exposure on the 25th (and its LRG success rate went from 0.96 to 0.99).

**Comment by ashleyjross** [comment]
Here is a histogram of the redshift success of LRGs for tiles in Jura:
<img width="586" alt="Screenshot 2024-08-27 at 3 22 10 PM" src="https://github.com/user-attachments/assets/d663df56-37a7-431e-94f2-5ed1092c5109">

**Comment by ashleyjross** [comment]
(this does include masking, both of fibers and around bright stars, that will improve the statistics, but 0.93 will always be an extreme outlier)

**Comment by schlafly** [comment]
I agree with you that 0.93 is impossibly bad in the context of that plot, but I also can't understand it in terms of anything the QA says.  So fine, I guess we call the 20240824 exposures on 11419 as bad.  1135 is not on my list of near-moon exposures, but 0.96 is also an impossibly bad outlier on that plot, so I guess we declare those exposures to be bad as well?  I'm worried that I would never have declared these images bad without this plot.

**Comment by ashleyjross** [comment]
I realized the 0.93 isn't the fair comparison there, because 0.93 is using DELTACHI2 > 25 & ZWARN==0 and I was using the LSS definition (which is DELTACHI2 > 15 & ZWARN == 0). The more fair histogram is:
<img width="586" alt="Screenshot 2024-08-28 at 2 22 47 PM" src="https://github.com/user-attachments/assets/93f2f19d-c949-4449-936c-60a7c1a3c055">
The combination of substantial improvement with some extra time from the 25th and you not finding anything wrong in the data makes me think that (for whatever reason) EFFTIME_SPEC is what is most corrupted in the data. The EFFTIME_ETC is more accurate, somehow, in that at those EFFTIME, we would start getting such low success rates, as this plot from Rongpu's targeting paper shows:
<img width="400" alt="Screenshot 2024-08-28 at 2 27 12 PM" src="https://github.com/user-attachments/assets/29c3a18c-1dcf-4900-9201-c737be9cf507">
So, the most conservative thing to do would be to reject the exposures, but I'm willing to live with two tiles that could have bad efftime estimates.

**Comment by ashleyjross** [comment]
(And both 11419 and 1135 appear affected by the issue...Maybe there is someone who can inspect what happened with the EFFTIME determination for those tiles?)

**Comment by schlafly** [comment]
Okay.  @sybenzvi , can you mark these tiles as unsure and then do MTLs, so we don't archive and MTL these two problem cases?  @akremin , can you mark the exposures on the 20240824 on tileid 11419 and 1135 as bad and then reprocess those tiles?

I don't know of any reason that EFFTIME or EFFTIME_ETC should be weird for two tiles.  I think the agreement there was at the ~20% level typical of moony exposures.

**Comment by geordie666** [comment]
@kremin: We need these exposures marked as bad and the tiles rerun.

**Comment by geordie666** [comment]
@akremin, I mean: Could you please mark this exposure as bad and rerun the tile?

**Comment by schlafly** [comment]
Just pinging this ticket again; as we finish the SGC these tiles are leaving a noticeable hole.

**Comment by akremin** [comment]
All exposures for 11419 and 1135 on 20240824 have been marked bad and removed. 
Both of these were re-observed on 20240825. Those redshifts were removed and rerun. 

I have updated the `exposures-daily` and `tiles-daily` files to reflect the changes in both nights.

**Comment by schlafly** [comment]
@SGontcho , can you reQA these?  Thanks!

**Comment by geordie666** [comment]
I've updated the `tiles-specstatus` file for `11419` and `1135`. @SGontcho: You don't need to take any further action.
