### ISSUE TITLE
Tile 6221 on 20241004 abnormal number of non-TGT on Petal 0

### ISSUE THREAD

**Issue by SGontcho** [desihub/desisurveyops#224]
Abnormal number of non-zero redshifts from non-TGT on Petal 0.
Tile QA-ed as "unsure". 

<img width="422" alt="Screenshot 2024-10-06 at 10 16 47" src="https://github.com/user-attachments/assets/dc70e942-e69b-46d7-899c-e6a3d6b06ff5">

**Comment by araichoor** [comment]
I think it s just because the tile is on the edge of the ls-dr9 footprint:
<img width="259" alt="Screenshot 2024-10-06 at 10 54 08 AM" src="https://github.com/user-attachments/assets/9391d135-c371-46fb-90a3-43c2604024e0">
so there are no science targets there, fiberassign fills the fibers with skies:
https://data.desi.lbl.gov/desi/target/fiberassign/tiles/trunk/006/fiberassign-006221.png

**Comment by schlafly** [comment]
This one got marked good, closing.
