### ISSUE TITLE
Bright tile 26056 redshifts wrong due to overscan cosmic on b1

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#28]
Bright tile 26056 observed in one exposure (expid 123247) on 2022-02-21 shows many spurious redshifts at z=0.14-0.15.  This is due to a cosmic landing next to (or on?) the overscan of B1 amplifier D.  Cosmic is at (2045,3707) in the raw image.  The row-by-row bias subtraction results in large negative (and significant) values at ~5600 Ang, which is eventually fit as H-beta in absorption for most fibers  in the range 500-749.

This will have to be solved by using both the bias region and the overscan region to filter out the effects of cosmics independent of bias level jumps.

**Comment by julienguy** [comment]
This is a really rare event of a cosmic ray totally saturating the CCD, bleeding in the overscan region.
I am reluctant to use the prescan region because it's only 4 pixel wide (so noisy to estimate bias level per row) and may lead to other issues. We may consider looking at a large charge deposit in the last CCD columns (read just before the overscan).
