### ISSUE TITLE
Bright tile 22889 with clustered sources around z=3.0-3.5

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#30]
Bright tile 22889 observed on 20220314 shows a bunch of clustered sources around z=3.0-3.5 on petal 4.
![unsure_tile22889](https://user-images.githubusercontent.com/1848618/158450212-b2a5733c-a28b-428e-833d-85aa5da97b0c.png)

**Comment by schlafly** [comment]
This is a 9th mag star a half arcsecond from a stuck fiber, fiber 2366.  This tile was designed before Dustin's tweaks went in, but the tweaked center would have been different.  So everything is working as expected here.  My impression is that if we masked this star's ~fiber bundle then everything would be fine, but I don't know if we have a device to do that.  Otherwise I guess we have to mask the whole petal.

@akremin , @julienguy , any sense for what the best option is here?

**Comment by schlafly** [comment]
Julien advocates for declaring amps B, D on b4, r4, z4.  Then we need to reprocess and reQA.

**Comment by schlafly** [comment]
This has been reprocessed and the problematic amped marked bad.  I've marked as good in QA; closing.
