### ISSUE TITLE
Weird behavior in r1 of TILE 5648 on 20220324; ion pump glow contamination

### ISSUE THREAD

**Issue by rongpu** [desihub/desisurveyops#34]
EXPID 127342-127345 are affected by this issue, although only 127342 (TILEID 5648) shows noticeable effects on the redshifts.
![sframesky](https://user-images.githubusercontent.com/16765087/160290960-1262c0b2-451f-49b3-81ca-60f5c51c1fdd.png)

QA for tile 5648, showing many objects with z=~0.09 in petal 1:

![tile-qa-5648-thru20220324](https://user-images.githubusercontent.com/16765087/160291029-b8e6ea5b-11e1-4242-bb0d-5bd321c706b3.png)

Example of a z=~0.09 spectrum in tile 5648:

![image (5)](https://user-images.githubusercontent.com/16765087/160291040-cd85d2c7-101f-4779-ad91-8b69b889f5d7.png)

**Comment by schlafly** [comment]
Here's an animation of the preproc files for r1 around 127342.
https://data.desi.lbl.gov/desi/users/schlafly/misc/20220324-r1-preproc.gif
Clearly r1 goes a bit haywire in 127342 and then works itself out.  I don't see anything in the night log.  I think @djschlegel might have even been on the call at that point, preparing for the observation of the following LyA tile.

It looks to me like the effect is low-order enough that @julienguy 's inter-bundle fitting code could be used on this one to good effect.  That would be another case where we need to turn this code on selectively to a particular set of exposures, like those from 20211226.

Alternatively, we mark this amp as bad and reprocess.  This went into the MTLs, so we'd need to go through that process, but that's fine.

**Comment by julienguy** [comment]
There is indeed an excess of 5 to 10 electron per pixel in r1 expid=127342, which fades away in the next exposures and becomes negligible at expid=127347 and above.
There is no excess background in previous exposures. There is no excess in any other camera (including b1,z1) so it's not an external light contamination.

**Comment by julienguy** [comment]
It might be related to a glitch in the SM10 red cryostat pressure I see in grafana.
The timing is not exact but this is intriguing. The spike in pressure is at 03:27 (on 2022-03-25) and the exposure with the highest background (expid=127342)  has DATE-OBS=2022-03-25T02:57:26 and an exposure time of 1093 sec.
![Screenshot from 2022-03-28 15-44-16](https://user-images.githubusercontent.com/5192160/160499805-64210440-4539-464f-9e29-b5c5c787fd22.png)
(see follow-up on slack instops channel if interested)

**Comment by julienguy** [comment]
(I edited my previous post to correct the value of DATE-OBS and the exposure time, the spike in pressure happened during the exposure)

**Comment by schlafly** [comment]
Wow, okay.  That's pretty definitive.

It's much more interesting to figure out what went wrong, here, but continuing to focus for the moment on how we should treat this particular tile: do you feel like we should try to model it via your preproc code, or mark them as bad (at least the first one)?

**Comment by schlafly** [comment]
And in case anyone else is interested... the spectrograph pressures are kind of interesting.  Here's the last week for a few different cryostats:
SM10 (peak is the one under discussion in this issue): 
![image](https://user-images.githubusercontent.com/1417841/160501667-340eb56a-9a44-4d45-818b-c9b2588d1e4a.png)
Tallest peak in the last week: 
![image](https://user-images.githubusercontent.com/1417841/160501715-6a656836-25f1-440c-8b61-a4d9060dc316.png)
Different time scales: 
![image](https://user-images.githubusercontent.com/1417841/160501780-f3a2a140-3398-4229-91ae-ca6c7ab60c88.png)
No idea what anything means, of course!

**Comment by julienguy** [comment]
I tested running the preprocessing with option `--bkgsub-for-science` . It does correct most of the effect. There is a residual systematic bias of 1 electron, but that should be acceptable. At least that would save several r1 exposures on the special tile 82636.

So I suggest rerunning r1 for exposures 127342 127343 127344 127345 127346 with the preproc option `--bkgsub-for-science`.

Example
```
desi_preproc -i $DESI_SPECTRO_DATA/20220324/00127342/desi-00127342.fits.fz --cam r1 --bias $DESI_SPECTRO_REDUX/daily/calibnight/20220324/biasnight-r1-20220324.fits.gz -o preproc-r1-00127342-bkgsub.fits --bkgsub-for-science
```
Plot comparing reductions without ('daily' prod) and with this option.
![Screenshot from 2022-03-28 16-17-38](https://user-images.githubusercontent.com/5192160/160503383-608e892a-319d-4a17-8113-1d459990f5cf.png)

**Comment by schlafly** [comment]
Great.  That means we don't take any actions here on the surveyops side; the issue didn't seem to affect LyA decisions, so we don't need to try to fix the MTL rapidly.  But I leave it open with the doesnotblockmtl flag until we devise the scheme to mark this exposure and exposures like it (20211226) as needing --bkgsub-for-science.

**Comment by cmvgit** [comment]
_About the ion pressure spike in SM10RED._
1-/ do not worry about the oscillations of Pion, they are low level and are present on all cryostats (when the ion pressure goes below ~7 to 8e-8 mbar
2-/ There are "electronic" spikes that occur from time to time on the ion pressure, no worry
3-/ The spike reported by Julien in SM10RED 25/3 3h30 UTC is **more worrying** because it is very high (~3e-5 mbar) and last for a long time (more than 2 hours to recover). Thus it is not related to electronic noise.
- I check all the parameters (LPT power, cryostat temperatures, pressure in the BLUE and NIR SM10 cryostats) -> all is OK.
This spike seems to have only affected the pessure, not the thermal nor the LPT.
Thus it seems to me unprobable that it could affect the CCD noise level.
- I check the behavior of SM10RED since 3/1/2022 and do not detect another important spike like this one.
4-/ Thus I do not know what has happened. **This really looks like some air has entered the cryostat.**
The only case where we have observed such a behaviour was on the Saclay test bench and it was due to a knock/schok on the cryostat pipe near the isolation valves. Although that seems not likely because it was around 20h30 24/3 Kitt-Peak time.
-> let's see if this kind of problem comes back (before changing the cryostat or the ion pump)
![sm10_Pion_0303-29032022](https://user-images.githubusercontent.com/25012565/160607052-e706043f-b328-47ea-83aa-6eefec0437e4.png)
![sm10red_Pion-bump_25032022-3h30](https://user-images.githubusercontent.com/25012565/160607088-103cafde-554b-47ee-892d-f8328fdea5a9.png)
![sm10red_Pion-bump_25032022-3h30_zoom](https://user-images.githubusercontent.com/25012565/160607094-86a9d5e6-ec3a-4ac8-8137-2bd4ae6791c5.png)
![sm10_Pion_0301-29032022](https://user-images.githubusercontent.com/25012565/160607105-add09b59-fb35-4202-a95a-a142d4f43be0.png)

**Comment by cmvgit** [comment]
Sorry I just realize that my github name was not really explicit: cmvgit == Christophe Magneville

**Comment by cmvgit** [comment]
Same problem on SN2/SM3 NIR:
- 26/3 2h42 UTC == 25/3 19h42 KP  and last for ~12h -> may be some dark? Bias? at that time
- Also identify a spike 22/2/2022 11h43 UTC last 2h
![sn2-sm3_Pion_bump_26032022-2h42](https://user-images.githubusercontent.com/25012565/160850904-e3fec49f-f063-4aeb-9682-432eada4b0d4.png)
![sn2-sm3_Pion_bump_0102-01032022](https://user-images.githubusercontent.com/25012565/160850922-999ccbb0-59a3-4b86-a625-e8e0584f0e89.png)
![sn2-sm3_Pion_bump_22022022-11h43](https://user-images.githubusercontent.com/25012565/160850938-6023ad1e-77fb-47cd-9f32-663d05b99cc1.png)

**Comment by julienguy** [comment]
Thanks Christophe. It's actually SM2 NIR which is 'z8'. 
We have 2 exposures that could have been affected by the pressure spike on 26/3 2h42 UTC :
NIGHT=20220325 EXPID=00127448 DATE-OBS=2022-03-26T02:36:49.259056896 (UTC)	exptime=720.5 	(BRIGHT)
NIGHT=20220325 EXPID=00127449 DATE-OBS=2022-03-26T02:51:30.593492992 (UTC)	exptime=1342.1 	(DARK)

Looking at median over rows in the preprocessed images. I detect a large offset of ~10 electron/pix for the first exposure=00127448 but a small/negligible effect for the second one (expid=00127449).

![Figure_1](https://user-images.githubusercontent.com/5192160/160887503-008cb9e6-6e6a-4026-a60e-475c87ca3ef8.png)

![Figure_2](https://user-images.githubusercontent.com/5192160/160887525-6c17379b-bbb4-45e3-bb4d-9cbf93c0d4d4.png)

We should also reprocess 127448 z8 with option --bkgsub-for-science .

**Comment by cmvgit** [comment]
OK. I was talking about SN2(winlight number)/SM3(cryostats production number Saclay) which is identified SM2 for you.
So we are talking of the same cryostat.
The first exposure include the transition between quiet/spike behavior. The second one cover the "end of the spike" but the level is not so high (~<3e-6 mbar).
For SM10 same issue: the "continuation of the spike" has a level even lower (~<1e-6 mbar) less than 720s after the transition
Seems that the light is generated just at the transition ?

**Comment by schlafly** [comment]
These exposures end up in the same class as 20211216, are waiting on a new pipeline feature which lets us specify special processing for a specific range of exposures.  @sbailey , is there a desispec issue I should associate these with?

**Comment by sbailey** [comment]
I just opened desihub/desispec#1740 to track the need for automated hooks for custom processing of some cameras/exposures.  We don't have a good solution even designed yet, much less implemented.

**Comment by geordie666** [comment]
Note there are two options:

(1) Remove this tile entirely from the MTL (the option we use if no overlapping tiles have been subsequently observed).

(2) Change the redshift/quality/classification information for the tile and reprocess the MTL as if we'd observed the tiles with the different information. 

The approach for option (2) is:

- Stephen (or someone similar) re-archives the tiles with the new information from the spectroscopic pipeline. This produces a second (or third, etc.) "archived" directory with a new `ARCHIVEDATE` for the tile and adds the new `ARCHIVEDATE` in the MTL tiles file.
- I execute `run_mtl_loop` [with the magic --reprocess option](https://github.com/desihub/desitarget/blob/2.6.0/bin/run_mtl_loop#L31-L32). This magically reverts all of our previous choices and replaces them with the updated choices.

**Comment by schlafly** [comment]
If we do (2) but no tiles have overlapped, is that equivalent to (1)?

**Comment by geordie666** [comment]
It's not really _equivalent_. In (1) all record of the tile in the MTL ledgers will completely vanish. In (2) we'll keep a careful record of the tile but we'll change the results arising from that tile.

(1) is easier (it's as if we just never reduced the tile, from an MTL perspective).
(2) is more honest (it notes we reduced the tile and updated our choices). But, it's more work because the spectroscopic pipeline has to produce new outputs for the tile (and re-archive the tile with those new outputs).

In the past, we've used (1) when we didn't overlap the tile and (2) --- because we really had to --- when we did overlap the tile.

**Comment by schlafly** [comment]
Sorry, right, the MTLs will not have identical rows.  But just making sure I'm understanding, they're equivalent in the sense that what we actually target for DESI will be the same in both cases?

In this case where we have already archived the tile and the tile is not completely bad, we'd need to reprocess & rearchive either way?

**Comment by geordie666** [comment]
Right, I believe both those statements are true _for tiles that haven't already been overlapped by a subsequent tile_.

Once we have observed a subsequent overlapping tile, we _also_ have to reprocess and rearchive, because simply removing the tile (1) does not self-consistently alter subsequent decisions in overlapping tiles like (2) does.

Note that, if you aren't sure whether the tile has been overlapped, we also wrote `desitarget.mtl()` code to check that.

**Comment by schlafly** [comment]
Okay, let's mark r1 as bad on 20220324, expid 127342-127345, and reprocess.  This is tileid (5648, 82636).  tileid 5648 needs to be reprocessed potentially in some kind of special mode so that zmtl's get created for P1 and can be used for the MTL reprocessing; I think Stephen is reviewing what we did there?  Some mixture of @sbailey , @abhi0395 , @marcelo-alvarez ?

**Comment by schlafly** [comment]
Pinging this ticket.

**Comment by schlafly** [comment]
Pinging this ticket.  We need to mark r1 as bad on 20220324, expid 127342-127345, and reprocess.  Then it will need to go to Stephen / Adam for rearchiving and including in the MTL.

**Comment by abhi0395** [comment]
@schlafly Re-processed except tile 82636. tsnr+nightqa updated. Some issue with 82636 (ticket (#134) is mentioned describing the problem)

**Comment by schlafly** [comment]
Just noting for myself, 127342 was on a main survey tile, while 127343-127350 were on 82636, some special program tile.  82636 is the problematic one, so we're missing a chunk of the night in the nightqa, but that's fine.

This is a a redo-MTL case, where we should rearchive 5648 with the new processing.  I don't think I need to do anything with the QA here, which is marked as good.  @sbailey , to you?

**Comment by sbailey** [comment]
@schlafly @geordie666 I have rearchived tile 5648 with
```
desi_archive_tilenight -n 20220324 -t 5648 --badpetals 1
```
Passing off to @geordie666 for MTL update.

Tile 82636 remains unprocessed due to issue #134 .

**Comment by geordie666** [comment]
Tile 5648 has been re-updated in the MTL ledgers.
