### ISSUE TITLE
Exposure ID 128784 on tile 23108 was out-of-focus

### ISSUE THREAD

**Issue by geordie666** [desihub/desisurveyops#38]
Exposure ID `128784` on tile `23108` was out-of-focus, leading to a high RMS across petals on that exposure. Here is the tile:

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23108/20220405/tile-qa-23108-thru20220405.png (this is the bad exposure)
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23108/20220406/tile-qa-23108-thru20220406.png

Here's a plot of the relative focus from Eddie:

![Out-of-focus](https://user-images.githubusercontent.com/13952581/162275135-0b57a297-e2da-4221-b025-7198496d2ec4.png)

See also https://github.com/desihub/desispec/issues/1738.

**Comment by schlafly** [comment]
@akremin , can we mark 128784 as bad and reprocess 23108, then I'll repeat QA?

**Comment by schlafly** [comment]
Following up this out-of-focus case with @crockosi , it turns out that we were slightly delayed in turning autofocus on, so the autofocus corrections from the initial focus loop were not applied to this exposure.  So we now understand how everything happened.

Action items could be:
- remind about logging out-of-focus exposures to night log and turning on autofocus
- maybe emitting a warning if the NTS is turned on while autofocus is off?
- including autofocus defocus measurements in header so that we can automatically flag these downstream?

Email from Connie:
The reason we were out of focus for exposure 128784 is that the LO hadn't enabled autofocus until after the slew to that field. So we were at the LUT plus temperature compensation value, not the  best focus as determined by the donut analysis.

Here is a Grafana plot of the same time range as Eddie sent me earlier, but I've included the "LUT configuration" panel.  The AOS option is not enabled until 2:42:38. The fits file for 128784 says that the sequence started at 2:38:21Z (fits header SEQSTART). 

![image](https://user-images.githubusercontent.com/1417841/162338701-b4f2e923-00f3-45e8-a32f-94e0437054e8.png)

**Comment by akremin** [comment]
Flagged exp 128784 on tile 23108 on 20220405 to ignore and removed the spectra and redshift files. Reran the redshifts for 20220406 so they don't include the earlier exposure on the previous night, and updated the summary tables and night QA for both nights. 

Done on the pipeline side.

**Comment by schlafly** [comment]
I've cleared the QA here.  Tile is not done so I have not yet repeated QA; tile should be reobserved "automatically" by the NTS one of these nights.

**Comment by schlafly** [comment]
@sbailey, can you help me understand what to expect with desi_update_tiles_specstatus?  This tile came up again for QA even though in tiles-daily.ecsv it has status = obsstart and low EFFTIME.  But in tiles-specstatus, post desi_update_tiles_specstatus, it still has status = obsend and high EFFTIME.  So it came up for QA and it was marked as bad again.  I was counting on its status in tiles-specstatus being updated to its reprocessed state, but that does not seem to be occuring.

**Comment by schlafly** [comment]
Closed with desi_update_tiles_specstatus --all --tileids 23108.
