### ISSUE TITLE
High read noise reported on R3B for expid 130556 due to CTE

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#41]
Exposure 130556 on BACKUP tile 42424 observed 2022-04-16 reports a high read noise on amplifier R3B with OBSRDNB = 10.58 e- (or 6.38 ADU).  This is apparently due to a bright (but not saturating) star next to the overscan, and  hysteresis/CTE pushing down the counts by approx 30 ADU immediately after that star.

Attached is a cut throw a portion of the raw image showing the effect where the star is at column 2197.
<img width="586" alt="Screen Shot 2022-04-17 at 12 02 26 PM" src="https://user-images.githubusercontent.com/7918018/163728829-cf31569b-94e6-4bd5-9baf-4cf1367b60ad.png">

**Comment by schlafly** [comment]
For this backup tile, we probably just won't fix this.  @julienguy , does this issue inspire you in any way?

**Comment by julienguy** [comment]
It's a rare event for which a software fix might do more harm than good (we had for instance many issues with the overscan step detection for instance). It's indeed due to a very bright star close to the overscan region, where the imperfections of the dark trail correction become visible. The positive offset is over-subtraction and the negative under-subtraction of the trail.

**Comment by schlafly** [comment]
Closing this as a "won't fix" problem affecting only backup tiles.
