### ISSUE TITLE
SP1 spectra from night of 2022-04-13 show different absorption dip due to new collimator

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#42]
One of the new replacement collimators was installed for the night of 2022-04-13 only, on SP1 (SM10).  It has a deep absorption at 420 nm, which is bluer than the dip in the original collimators.  Only BRIGHT tiles were observed on that one night.  The reduced data do show uncorrected flux-calibration residuals around this new dip, although the BGS redshifts appear robust to this.  A couple of representative calibrated spectra attached.
<img width="597" alt="Screen Shot 2022-04-14 at 1 09 34 PM" src="https://user-images.githubusercontent.com/7918018/163731310-5ada9f76-6e3a-49b4-be00-86f87d575f31.png">
<img width="591" alt="Screen Shot 2022-04-14 at 1 15 31 PM" src="https://user-images.githubusercontent.com/7918018/163731311-27f4fda7-4c86-495f-8099-53713f246d15.png">

**Comment by schlafly** [comment]
We discussed this on the survey-ops call and the decision was to not do anything, since:
- we expect this only to cause problems insofar as the humidity changed between the flat field and observations
- we have many such exposures ithe main survey
- this was for bright tiles for which we have no examples of this ever leading to spurious redshifts.

If we learn otherwise in the future we treat this as bad hardware and update the MTL to have all P1 exposures from 20220413 marked as bad.
