### ISSUE TITLE
Tileid=3298: accumulation of Z~0.25 for FIBER around 1900

### ISSUE THREAD

**Issue by araichoor** [desihub/desisurveyops#47]
This TILEID=3298 has been observed on 20220519 with EXPID=134023.
It has been marked as good.

Nevertheless, there is an accumulation of Z~0.25 for 1890 < FIBER < 1912 (approximate range).
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/3298/20220509/tile-qa-3298-thru20220509.png
![tile-qa-3298-thru20220509](https://user-images.githubusercontent.com/61986357/168505915-5834d0b8-b54c-4fa5-9afd-f1dd800d38dd.png)

There is a drop in the flux at lambda~4660A (you can see it when a different z is picked), which is often interpreted at a negative oii flux:
[tmp-3298-thru20220509-1890fiber1911.pdf](https://github.com/desihub/desisurveyops/files/8696543/tmp-3298-thru20220509-1890fiber1911.pdf)

Maybe some fibers in that range could be marked as bad.

Original slack message: https://desisurvey.slack.com/archives/C01HNN87Y7J/p1652218526122329

**Comment by schlafly** [comment]
@julienguy will love this; hysteresis effect from a bright cosmic ray?
![image](https://user-images.githubusercontent.com/1417841/168657942-f1ab03fe-7f06-46e3-ba2f-84a754732e0c.png)
http://desi-7.kpno.noao.edu:8001/20220509/00134023/preproc-r3-00134023-1x.html

**Comment by schlafly** [comment]
@julienguy, I'm assigning this to you, but feel free to just close.  This was a weird case where it looks like a cosmic ray in the middle of the detector led to a dark trail which led the adjacent ~20 fibers it crosses to have spurious redshifts.  r3.

**Comment by julienguy** [comment]
There is a dark trail issue + some unmasked pixels on the edges of this very bright cosmic trail.
![Screenshot from 2022-08-15 15-08-13](https://user-images.githubusercontent.com/5192160/184727214-4769a5e3-0a84-4070-9923-6a54b3a8242e.png)

The spectra show both a dip because of the dark trail and some spikes because of the unmasked edge pixels. The dominant effect is the dark trail.

Fibers 400 to 410 (+3500):
![Screenshot from 2022-08-15 15-10-41](https://user-images.githubusercontent.com/5192160/184727660-7b7bc727-6683-478e-8cb7-5cf77c352776.png)

The dark trail amplitude parameter was erroneously removed from the CCD configuration file. Adding it back to the original value fixes the trail issue:
![Screenshot from 2022-08-15 15-18-43](https://user-images.githubusercontent.com/5192160/184728531-0b56625d-62c7-47dc-97ca-d50bdc5a4a08.png)

I have committed the change to DESI_SPECTRO_CALIB. So one would just need to rerun this exposure. Maybe @akremin can add this one to the list. It is a single exposure / camera.

**Comment by schlafly** [comment]
Thanks Julien!  @akremin, this is tileid 3298, 20220519/134023.  We'd want to reprocess and then I'll repeat QA.

**Comment by sybenzvi** [comment]
@julienguy, you are correct that the binary closure used to repair gaps in the cosmic tracks causes the spurious merger of cosmics (see before and after plots below).

It may be possible to use a kind of directional fit in the dilation to avoid merging distinct cosmics, but it would have to work on both "tracks" and "worms." Before devoting effort to that, how critical a problem is over-masking, in your opinion? You said the dark trail (now fixed) was the major issue. Beyond that, my gut feeling is that under-masking in the [binary dilation step](https://github.com/desihub/desispec/blob/3bad78d4cddbfb459b09d5fe7423d9b007b88820/py/desispec/cosmics.py#L440) is a bigger problem than overmasking in the [binary closure step](https://github.com/desihub/desispec/blob/3bad78d4cddbfb459b09d5fe7423d9b007b88820/py/desispec/cosmics.py#L459). Thoughts?
![preproc_r3_20220509_00134023_norepair](https://user-images.githubusercontent.com/7385438/184980898-292f8675-02ee-410f-a516-f68affa0915e.png)
![preproc_r3_20220509_00134023](https://user-images.githubusercontent.com/7385438/184980908-c7bad1a8-98a5-485f-ae5d-034a775925b8.png)

**Comment by julienguy** [comment]
It is not critical (otherwise we would have already fixed it), but it would be an interesting project to work on.

**Comment by sybenzvi** [comment]
> It is not critical (otherwise we would have already fixed it), but it would be an interesting project to work on.

Yeah, it strikes me as a neat machine vision problem to chew on ;)

**Comment by akremin** [comment]
This was marked as good originally and was archived on 20220511. Are you advocating for reprocessing, re-archiving, and re-mtl-updating? @schlafly 

Otherwise we can close this ticket; leaving things as-is in daily but with future prods picking up Julien's change automatically.

**Comment by schlafly** [comment]
Ugh, thanks for being careful @akremin .  No, okay, I'll close, and I guess this is a candidate for closed_issues.csv.
https://github.com/desihub/desisurveyops/commit/325e3b725c7e3c314590d83132a915a5675aa047
