### ISSUE TITLE
BRIGHT tiles that hang off footprint and have weird redshift distribution

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#5]
There are a few otherwise fine tiles that hang off the edge of the footprint and have a weird redshift distribution.  I don't understand what is going on with these.  I don't know where we're getting off footprint redshifts?  I don't know if these are failures of real targets or just weird targets?

There may be many more cases that never got marked unsure.

Affected tiles: 20682, 21347, 23401, 25506

https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/20682/20211211/tile-qa-20682-thru20211211.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/21347/20220109/tile-qa-21347-thru20220109.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23401/20211218/tile-qa-23401-thru20211218.png
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/25506/20211211/tile-qa-25506-thru20211211.png

I'm leaving these as unsure; at least they're all on the edge of the footprint so they aren't so problematic from a depth-first perspective.

**Comment by schlafly** [comment]
@araichoor , I took a look at this one.  For the first case, ~all of the z > 0.5 redshifts on P5 are in fact OBJTYPE in ['', 'BAD', 'SKY'].  I would have guessed that these should be colored yellow and therefore not a cause for concern.  If you verify this, I'll go ahead and change these tiles to good.

**Comment by araichoor** [comment]
I've looked at the first case: my bad, those indeed are `OBJTYPE="SKY"` and should be colored in yellow.
I missed those `(DESI_TARGET & SUPP_SKY)` fibers, which corresponds to regions outside the dr9 footprint.
I confirm you can change them to "good"; thanks!

The reason is that the `OBJTYPE` column is not present in the `tile-qa*fits`, hence I've to find an indirect way to do that...
I identify the non-TGT with:
- BAD|SKY in DESI_TARGET,
- or UNASSIGNED|STUCKPOSITIONER|BROKENFIBER in QAFIBERSTATUS.
(here: https://github.com/desihub/desispec/blob/6f1bb4e2c49e69fb087df83ecbd2ef723e5c3d39/py/desispec/tile_qa_plot.py#L1344-L1348)

I'll make a PR to update desispec.tile_qa_plot.py (good test case to validate the desisurveyops / desispec

**Comment by schlafly** [comment]
Awesome, thanks Anand.  I've marked these as good now, but I'll leave the ticket open until you merge the PR.

**Comment by schlafly** [comment]
PR is merged, closing.  Does not actually affect redshifts & MTLs, so no need to go into closed_issues.
