### ISSUE TITLE
Tileid 25103 marked as unsure

### ISSUE THREAD

**Issue by forero** [desihub/desisurveyops#52]
Tileid 25103 was observed with exposure 136464 on 20220523.  It has multiple sky substraction warnings and a strong redshift clumping around z=0.75 across five petals (although the sky substraction warnings and the clumping might be unrelated).

<img width="1184" alt="Screen Shot 2022-05-24 at 1 06 53 PM" src="https://user-images.githubusercontent.com/1848618/170121129-b1d6428e-caa1-4570-88d4-63d16c97c562.png">

The sky substraction on petal 7 is definitely problematic

<img width="1155" alt="Screen Shot 2022-05-24 at 1 10 06 PM" src="https://user-images.githubusercontent.com/1848618/170121141-0920dcd5-35d1-49f2-8dfb-373e3b17f342.png">

**Comment by schlafly** [comment]
This is due to the very bright star on P7 whose halo also impinges a bit on P8.  We won't be able to block that star so we should mark this as good.  The cluster at z=0.17 is interesting but appears to be real.  I inspected ~20 objects in it on P6 and they all looked real to me.  I'm not actually seeing a cluster at 0.75 so I may not have been looking at what you intended.  In any case, as far as I can tell this is fine to mark good, since we won't be able to recover P7 no matter what we do.

**Comment by forero** [comment]
I misstyped, I meant z=0.15, not z=0.75. Anyway, tomorrow I will mark the tile as good. Thanks for checking!
