### ISSUE TITLE
Tile 4215 marked as unsure: lots of flagged fibers on P4.  Poor positioning due to fast sequencer & long slew before fix.

### ISSUE THREAD

**Issue by dstndstn** [desihub/desisurveyops#54]
![tile-qa-4215-thru20220530](https://user-images.githubusercontent.com/1065981/171287899-ea2e2f22-5c6a-4226-a705-d924d817b3c2.png)

**Comment by dstndstn** [comment]
Eddie says "It doesn't have typical defocus behavior, but it isn't really plausible that P4 has only 0.8 throughput."

Anand says "for what is worth, it looks like it s the first half of the fibers which are more affected by that."

**Comment by schlafly** [comment]
@julienguy , mind taking a look at this?  I'm surprised by the low THRUFRAC on P4.  It did not look to me like an obvious defocus case.  The turbulence is a bit odd but affects ~half the focal plane and doesn't look so bad to me.  I'm not sure what's up.

**Comment by schlafly** [comment]
This looks to be one of the cases where it's the first tile after the slew to the SGC, following the upgrade to the fast sequencer.  I think I thought this was fixed but I am not sure I've verified that.

**Comment by schlafly** [comment]
Judging by my past emails, the fix was implemented on 6/12, and we only had one very bad night's observing before the shut down after that.  We clearly still had fast sequencer & long slew issues on 6/11
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20220611/tileqa-20220611.pdf
We need to check this again after restart.  This is in principle something we could test before the spectrographs come on, but after the focal plane is ready?

**Comment by schlafly** [comment]
I've marked this tile as good and am closing, those we still need to check that the fast sequencer is now working well for long slews.  I think the fix was implemented and involved waiting for the ADC (which is fast), but my memory is hazy.
