### ISSUE TITLE
Mark bad guiding EXPID as bad, and reprocess

### ISSUE THREAD

**Issue by schlafly** [desihub/desisurveyops#74]
Starting on about Halloween night 2022-10-31, we started having guiding problems that significantly impacted survey speed and calibration homogeneity.  Anand recommended the quantity
ratio = FIBERFAC / (FIBER_FRACFLUX * TRANSPARENCY / FRACFLUX_NOMINAL_POINTSOURCE)
from the GFA matched coadds as a measure for the impact of guiding errors.  I've included here a list of all exposures between 2022-10-31 through 2022-11-14 which have ratio < 0.88.  We'd like to mark these as bad in the pipeline and then reprocess them, so that these exposures no longer contribute EFFTIME to their respective tiles.

https://data.desi.lbl.gov/desi/users/schlafly/misc/badguidingtileexp.ecsv

We have a measurement of the ratio for each GFA camera.  At present I'm using the worst value of ratio to determine whether or not to flag, but I could instead use a mean or median or something.  There is some scatter there.  Here's an example of the exposures that get marked (red lines) as a function of EXPID and their corresponding ratios.

![image](https://user-images.githubusercontent.com/1417841/202299489-6be91d91-6b66-4b38-b7ed-f4c8999ade2b.png)

@djschlegel , @araichoor , would you care to review, and then I'll ping Marcelo to actually do the reprocessing?

**Comment by araichoor** [comment]
your list apparently goes to 2022112, and contains 222 exposures (with at most six measurements per exposure).

working from `https://data.desi.lbl.gov/desi/survey/GFA/offline_matched_coadd_ccds_SV3-thru_20221115.fits`:

this catalog has 3 extensions, see https://desi.lbl.gov/trac/wiki/Commissioning/conditions#aggregatedextensions.
following Aaron s advice, for my cases, I ve always worked with the 3rd extension, which is supposed to provide cleaner measurements, one per expid.
one option could be to just use that 3rd extension? or we could use the full information from all gfa cameras, as you do.
just, I m not sure how "robust" each measurement is for individual cameras.

some numerology:
in the 3rd extension of the offline catalog mentioned above, I count:
- 413 exposures with NIGHT>=20221031 (and 307 with 20221031<=NIGHT<=20221112)
- 93 exposures with  NIGHT>=20221031 and RATIO<0.88 (and 91 exposures with  20221031<=NIGHT<=20221112 and RATIO<0.88)

your current list thus contains 222/307 of the exposures.
cutting on the 93/307 identified with the 3rd exposure is closer to "our goal" of rejecting ~25% only of the exposures, no?

remark:
my numbers also shows that only 2/106 of the 20221112<=NIGHT<=20221115 exposures are flagged.
if useful, I m sharing here a plot I ve made after Connie s remark on slack that the hour angle could play a role.
I cannot quickly compute that, but at least there seems to be some dependency with the airmass, so likely where we point.
i.e. there may be another parameter to use to better identify those.

<img width="1362" alt="Screenshot 2022-11-16 at 5 34 16 PM" src="https://user-images.githubusercontent.com/61986357/202332227-cb1733b7-52a2-4cf4-86ab-e517df4d8c80.png">

**Comment by araichoor** [comment]
thanks for the explanations.
this last list sounds good to me; don t know if @djschlegel has other comments/suggestions.

**Comment by schlafly** [comment]
@marcelo-alvarez , could you please mark the exposures listed in 
https://data.desi.lbl.gov/desi/users/schlafly/misc/badguidingtileexp.ecsv
as bad, and then reprocess the corresponding tiles?  We need to get the accumulated EFFTIME on those tiles updated so that NTS knows it is able to observe them again.  I don't actually know the details about how Anthony usually does this; I'm hoping @sbailey can help.

There are 91 tiles listed there covering the nights 2022-10-31 to 2022-11-12 (no exposures were flagged on 2022-11-13, and we called the problem solved on 2022-11-14).  

(Note: I had an original version of this file at this same location, and a newer version that also had a "2" in the file name.  I have since deleted the original version and renamed the newer version with the original name---there is now only one file so one can't accidentally grab the wrong one.)

**Comment by marcelo-alvarez** [comment]
@schlafly thanks for this, I will try to mark these exposures as bad and reprocess those tiles. 

@sbailey can you confirm that the steps to do this on cori would be:

First for each exposure EXPID mark the it bad in the exposure tables by running:
```
desi_edit_exposure_table -n $NIGHT -e $EXPID --include-comment "bad guiding" --overwrite-value -c LASTSTEP -v ignore
```
and then for each tile $TILEID that these exposures were on, run:
```
desi_purge_tilenight -n $NIGHT -t $TILEID --not-dry-run
```
and then reprocess for each night NIGHT with N tiles TILEID1,...,TILEIDN that were affected, by running:
```
desi_run_night -n $NIGHT --tiles=$TILEID1,...,$TILEIDN --z-submit-types=cumulative --laststeps="all,skysub,fluxcal" --all-tiles  --use-specter --append-to-proc-table &>>${HOME}/daily/logfiles/daily-${NIGHT}.log &
```

**Comment by araichoor** [comment]
if I got it right, I confirm that there are some tiles where only some exposures of a night are flagged (@sbailey):

```
b = Table.read("/global/cfs/cdirs/desi/users/schlafly/misc/badguidingtileexp.ecsv")
e = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.fits", "EXPOSURES")
for night in np.unique(b["NIGHT"]):
    for tileid in np.unique(b["TILEID"][b["NIGHT"] == night]):
        b_sel = (b["NIGHT"] == night) & (b["TILEID"] == tileid)
        e_sel = (e["NIGHT"] == night) & (e["TILEID"] == tileid)
        if b_sel.sum() != e_sel.sum():
            print("{}\t{}\t{}/{}".format(night, tileid, b_sel.sum(), e_sel.sum()))
```
returns:
```
# NIGHT TILEID NFLAGGED / NOBS
20221031	1304	1/2
20221031	2708	1/2
20221031	6923	1/2
20221031	8494	1/2
20221031	11414	1/2
20221105	8703	3/4
20221105	25559	1/2
20221106	25564	1/2
20221110	23283	1/2
20221110	24170	1/2
20221112	3112	1/2
20221112	25522	1/2
```

note that I ve not filtered here on `EFFTIME_SPEC > 0`, don t know if that should be done.

**Comment by sbailey** [comment]
@marcelo-alvarez thanks for documenting the commands.  A few comments on procedure:

> desi_edit_exposure_table -n $NIGHT -e $EXPID --include-comment "bad guiding" --overwrite-value -c LASTSTEP -v ignore

I suggest *not* including `--overwrite-value` by default and running these commands night-by-night so that it warns us if we are changing a non-default value before resorting to using `--overwrite-value`.  It probably doesn't matter for this case of setting LASTSTEP=ignore, but I try to follow this procedure because e.g. it is important for flagging a bad camera, because there might already be another camera flagged as bad and you don't want to replace one bad camera with a different one, you want to flag both as bad.

> desi_run_night -n $NIGHT --tiles=$TILEID1,...,$TILEIDN --z-submit-types=cumulative --laststeps="all,skysub,fluxcal" --all-tiles  --use-specter --append-to-proc-table ...

I don't think you need to list the tiles because it should pickup any unprocessed exposures and run those, but double check that.  I also think it would be fine to not specify --laststeps and just have it process the default of "all" (i.e. only process the exposures that are good enough to make it through to redshifts anyway).

And then after it is all over, we'll need to rerun `desi_tsnr_afterburner` to remake the exposures and tiles files with the updated values for the tiles on those nights.

**Comment by marcelo-alvarez** [comment]
Processing up to tsnr is complete, and nightqa is currently running, with the previous nightqa for NIGHT in `/global/cfs/cdirs/desi/spectro/redux/daily/nightqa/NIGHT.orig`

The new n(z) plots generated by nightqa currently don't look correct and most reprocessed tiles that still had an exposure are labeled as invalid, I assume because QAFIBERSTATUS > 0 for the vast majority of targets on reprocessed tiles and only the numerator changed in efftime/goaltime, respectively. 

See for example 
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20221031/tileqa-20221031.pdf
and
https://data.desi.lbl.gov/desi/spectro/redux/daily/nightqa/20221031.orig/tileqa-20221031.pdf

@schlafly do we need to modify the how nightqa runs on the reprocessed tiles in order to obtain intelligible nightqa output, or do you have the information you need just from the reprocessed outputs?

**Comment by araichoor** [comment]
there is definitely something weird, e.g.:
<img width="1258" alt="Screenshot 2022-11-22 at 9 43 01 PM" src="https://user-images.githubusercontent.com/61986357/203478082-31d39d8f-0018-437f-ab40-9e441c6ca8e6.png">
with those dark tileids with only one exposure with ~500s, it is normal that e.g. `efftime/goaltime` is flagged as red, because `goaltime=1000s` for dark tiles.

what is not normal is that there are some fibers with `QAFIBERSTATUS = 0`, because all fibers should have the `LOWEFFTIME` bit turned on:
https://github.com/desihub/desispec/blob/46f5a9f84075c4740db06375a442c392cf68c626/py/desispec/tile_qa.py#L292-L293
```
    low_efftime_fibers = np.where(tile_fiberqa_table["EFFTIME_SPEC"] * (ebvfac_fibers / ebvfac_med) ** 2 < minimal_efftime)[0]
    tile_fiberqa_table['QAFIBERSTATUS'][low_efftime_fibers] |= fibermask.mask("LOWEFFTIME")
```
for this example, the 30 main (+3 not-main) targets with `QAFIBERSTATUS = 0` have `EFFTIME = 12.15 x TSNR2_LRG < 600s`, so should be flagged.
[a "normal" case is e.g. tileid=2746, where all fibers have `QAFIBERSTATUS>0`, hence none is plotted in the n(z)].

if useful, those mostly are on petals 4 and 5 (one being on petal 1):
<img width="1117" alt="Screenshot 2022-11-22 at 9 55 10 PM" src="https://user-images.githubusercontent.com/61986357/203480677-55c75fe0-c032-4189-900f-77681b05d4f0.png">

I can try to investigate what s going, but not sure I ve the cycles right now...

**Comment by araichoor** [comment]
"_it sounds like it should have had none instead._" => yes

"_as long as the tiles have the appropriately reduced efftime, then I suppose the reprocessing did what it was supposed to do._" => well, in a kind of buggy way I think, as those ~30 targets with `QAFIBERSTATUS = 0` should have `QAFIBERSTATUS>0`.
it means that those targets won t be put back for re-observation, as the pipeline considers they accumulated enough efftime.
but more fundamentally, this means that there is something unexpected in the pipeline -- at least to me! -- and that we should understand+fix that.

**Comment by araichoor** [comment]
actually, I ve re-run on my side the code with additional prints, and it looks like nothing is wrong.
I may have been misled by a wrong recollection of not seeing that before...
sorry for the false alarm!

details:
so, for TILEID=8494, the code uses:
- `ebvfac_med = 1.1439182542908803`
- `minimal_efftime = 722.4999999999999` (which is fiber_rel_mintfrac * mintfrac * goaltime = 0.85 * 0.85 * 1000)

I ve looked at `TARGETID=39627893336182059`, which has `QAFIBERSTATUS=0`:
- `tile_fiberqa_table["EFFTIME_SPEC"][i] = 663.8833` [this actually comes from TSNR2_ELG; known "issue"]
- `ebvfac_fibers[i] = 1.195541`
- `tile_fiberqa_table["EFFTIME_SPEC"][i] * (ebvfac_fibers[i] / ebvfac_med) ** 2) =  725.1548071512476`

so, that is indeed above the `minimal_efftime` value, so nothing wrong.

and this plot shows in the x-axis the quantity used by the code, so it looks ok, with `QAFIBERSTATUS=0` fibers being rightward of the red vertical line:
![tmp](https://user-images.githubusercontent.com/61986357/203501123-ba460fdf-9475-4729-8060-0b91eab3fc25.png)

**Comment by marcelo-alvarez** [comment]
@araichoor thanks and sorry for raising the false alarm in the first place with my misinterpretation of the noisiness in the reprocessed nightqa n(z) histograms. 

@schlafly please disregard my previous question - as far as I can tell the reprocessing worked. Please let me know if you need anything else for this.
