### ISSUE TITLE
Tile 7946 exposure 154927 from 20221126 needs processing + QA

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desisurveyops#87]
Processing for tile 7946 on 20221126 failed initially because of a bug in the spectroscopic pipeline. The bug was fixed in https://github.com/desihub/desispec/pull/1927, but this tile did not get reprocessed before Perlmutter was shutdown for maintenance. 

I will update here when this tile is processed and ready for QA.

**Comment by schlafly** [comment]
Just FYI: if a tile never reaches QA (e.g., because processing didn't proceed far enough to generate the tile-qa.png files, then we'll automatically see it when processing is successful and we next run desi_tile_vi (i.e., ~daily).  So if we don't see a tile because of a processing failure we usually don't need to track that separately in an issue.

We need to be more careful about tracking tiles in issues when we do see the tiles but mark them as unsure.  After being marked unsure, tiles will remain unsure indefinitely until we intentionally decide to QA them again.  Usually we do that because component exposures have been marked bad, etc..  That kind of tile makes up a good fraction of all of the issues on this board.

Tile 7946 looks to be of the former case where on the QA side we don't need extra tracking of this exposure.  On the other hand, on the spectroscopic side of course one doesn't want to lose track of this!  We hadn't been using this board for that case, but if that's useful we should attach a new label to it.

**Comment by marcelo-alvarez** [comment]
Thanks for explaining about this. I will leave this ticket here, but will close it once the tile is ready for QA. In the future I'll open tickets like this one in desispec.

It is good to know that newly processed tiles are automatically picked up when ready for QA. If I understand correctly, this means that processing successful tiles through to tsnr+nightqa for a given night will not cause any errors on the QA side, as long as we remove / rename any files that would trigger QA for unsuccessful tiles from the same night. Please let me know if I'm missing something and thanks again for helping me get up to speed on QA - offline interface.

**Comment by schlafly** [comment]
QA is triggered when:
- a tile is recorded in tiles-daily to have more than the required amount of effective time
- a corresponding tileqa file is found that can be displayed to the person doing QA
If processing just fails, I think neither of these usually applies and the tiles won't be picked up for QA.

Yes, if other tiles on the night do have enough time in tiles-daily and do have tileqa files, they'll be picked up and QAed.  I think we're on the same page?

**Comment by akremin** [comment]
Marcelo, waiting for all tiles to be handled before running tsnr and
nightqa is a data-ops strategy rather than a constraint imposed by
survey-ops. The strategy is partly historical before we had the sanity
check in place that we have now, but it also ensures that we don't miss
anything and reduces the number of desispec tickets we need to track. If we
can resolve issues before signing off on a night, then we can confidently
move on without worrying about a lingering tile impacting a tile on a
future night, etc.

It's a strategy, not a strict rule, and if there is a particularly
problematic software fix we may go against the strategy, but in general it
has served us well up to this point.

Note this is before survey-ops quality assessments, where they may flag
processed data as bad. That follows the standard mechanisms you're now
familiar with, with surveyops github tickets.

**Comment by marcelo-alvarez** [comment]
Thanks Eddie and Anthony for the explanations -- this is all clear to me now. Although the tile in question is not yet reprocessed, I will go ahead and close this ticket now since it requires no further action by survey-ops.
